### PR TITLE
Feature 2615 main v11.1 gcc12

### LINKED ISSUE #2615: Bugfix: Problem compiling MET on MacOS using GCC 12.3.0
## Describe the Problem ##
The compilation of MET-11.1.0-rc1 on the MacOS fails when compiling with gcc 12.3.0, but succeeds with gcc 11.3.0.  The error in the make.log file (attached) is the following when making pb2nc:
[met.make.log](https://github.com/dtcenter/MET/files/12100683/met.make.log)

Note that a libbufr.a file is created from the BUFRLIB compilation, but I noticed this in the log file:

> file: libbufr.a(modv_MXH4WLC.o) has no symbols

[bufr.make.log](https://github.com/dtcenter/MET/files/12100702/bufr.make.log)

```
calcape.f:442:72:

  442 |  510    POLD(KP)=P
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 510 at (1)
calcape.f:464:72:

  464 |  530    QSNEW(KP)=QSNEW(KP-1)+DQS
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 530 at (1)
calcape.f:472:72:

  472 |  540    PTBL(KP,KTH)=PNEW(KP)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 540 at (1)
calcape.f:485:72:

  485 |  560    THEOLD(KTH)=TH*EXP(ELIWV*QS/(CP*TOLD(KTH)))
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 560 at (1)
calcape.f:509:72:

  509 |  580    THENEW(KTH)=THENEW(KTH-1)+DTHE
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 580 at (1)
calcape.f:517:72:

  517 |  590    TTBL(KTH,KP)=TNEW(KTH)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 590 at (1)
pb2nc.cc:147:31: error: variable 'const std::array<int, 6> var_gc' has initializer but incomplete type
  147 | const std::array<int, mxr8vt> var_gc = {
      |                               ^~~~~~
pb2nc.cc:151:32: error: aggregate 'std::array<int, 6> bufr_var_code' has incomplete type and cannot be defined
  151 | static std::array<int, mxr8vt> bufr_var_code;
      |                                ^~~~~~~~~~~~~
pb2nc.cc:157:36: error: variable 'const std::array<int, 6> derive_gc' has initializer but incomplete type
  157 | const std::array<int, n_derive_gc> derive_gc = {
      |                                    ^~~~~~~~~
mv -f .deps/pb2nc-pb2nc_conf_info.Tpo .deps/pb2nc-pb2nc_conf_info.Po
make[5]: *** [pb2nc-pb2nc.o] Error 1
```

Another user, @HathewayWill, also tested on a Mac using gcc 12.3.0 and received the same error his met.make.log file.  A copy of his files are linked to in his [comment](https://github.com/dtcenter/MET/issues/2596#issuecomment-1642941330) on another issue.  

### Expected Behavior ###
MET-11.1.0-rc1 should build on the MacOS using gcc 12.3.0.

### Environment ###
Describe your runtime environment:
*1. Machine: Mac Laptop*
*2. OS: MacOS Monterey version 12.6.7*
*3. Software version number: MET-11.1.0-rc1*

### To Reproduce ###
Describe the steps to reproduce the behavior:
Attempt to install MET and its dependent libraries using the compilation script [here](https://raw.githubusercontent.com/dtcenter/MET/bugfix_2596_main_v11.1_rpath_compilation/internal/scripts/installation/compile_MET_all.sh) or after this [PR](https://github.com/dtcenter/MET/pull/2614) is merged, using the script in main_v11.1, on a MacOS using gcc 12.3.0.

### Relevant Deadlines ###
Preferably before the 11.1.0 release.

### Funding Source ###
2792543

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
I implemented the code changes and compile with gcc 12.3.0 on my MacOS.  @hsoh-u also compiled successfully with these changes.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Review the code changes.  Ensure that all tests pass.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[20230726]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by hsoh-u — APPROVED** [review]
I tested this at cheyenne with gnu 12.1.0.
