### ISSUE TITLE
nc_var_info.cc:15:10: fatal error: 'netcdf' file not found

### ISSUE THREAD

**Issue by wxbinge** [dtcenter/MET#2952]
I have compiled installed NetCDF-C and NetCDF-CXX to compile several packages. However, when I try to compile MET, the package cannot find NetCDF, and I am trying to figure out what I need to do differently. I am using a bash environment. Here are my setup and procedures:

**MET Version:** 11.1.1

**Compilers:** Intel OneAPI (icx and icpx)

**Issue:** Unable to find NetCDF

<img width="796" alt="image" src="https://github.com/user-attachments/assets/e1726532-0a77-43f6-93ae-a48d3b6a5719">

NetCDF directory: I've read that NetCDF-C and NetCDF-CXX must be in the same directory.

<img width="383" alt="image" src="https://github.com/user-attachments/assets/4cb53d64-c2a0-45ab-95a1-e15121bd756d">

**In the .bashrc:** export MET_NETCDF=/home/wxbinge/work/built_with_intel_2024_old_libs_version_2.1/netcdf

I've attached my config.log, config.status, and make log files.
[config.log](https://github.com/user-attachments/files/16737482/config.log)
[config.status.txt](https://github.com/user-attachments/files/16737484/config.status.txt)
[make.log](https://github.com/user-attachments/files/16737524/make.log)

**Additional Notes:** I've also tried including the MET_NETCDFINC and MET_NETCDFLIB paths in the bashrc file, but I am still getting the same error. I've tried to use the CPPFLAGS when setting up the configuration. 

Any assistance would be greatly appreciated.

**Comment by wxbinge** [comment]
It seems the netCDF libraries I am using are too old to compile with MET v11.1.1. 

I used some newer netCDF builds on my system and got past the error. However, I am now faced with this error:

/usr/bin/ld: /home/wxbinge/work/built_with_intel_2024_old_libs_version_2.1/netcdf/lib/libnetcdf_c++4.so: undefined reference to `nc_inq_var_filter'
/usr/bin/ld: /home/wxbinge/work/built_with_intel_2024_old_libs_version_2.1/netcdf/lib/libnetcdf_c++4.so: undefined reference to `nc_def_var_filter'
icpx: error: linker command failed with exit code 1 (use -v to see invocation)

Has MET been tested with Intel OneAPI compilers (icx and icpx)?
